services:
  # Use type: pserv if you want it private-only
  - type: web
    name: grobid
    runtime: image
    image:
      url: docker.io/lfoppiano/grobid:0.8.2   # official image
    plan: starter
    healthCheckPath: /api/isalive
    envVars:
      - key: JAVA_OPTS
        value: -Xms512m -Xmx4g
